services:
  mongodb:
    image: mongo:latest
    container_name: pharmacy-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "akshay134"
      MONGO_INITDB_ROOT_PASSWORD: "Akshay@134"
    restart: always
    networks:
      - pharmacy_medicine_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pharmacy-app:latest
    container_name: pharmacy-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - pharmacy_medicine_network
    restart: always

volumes:
  mongo-data:

networks:
  pharmacy_medicine_network:
    driver: bridge